const fs = require('fs');
const { createClient } = require('@supabase/supabase-js');

const env = fs.readFileSync('.env.local', 'utf8');
const supabaseUrlMatch = env.match(/NEXT_PUBLIC_SUPABASE_URL=(.*)/);
const supabaseServiceKeyMatch = env.match(/SUPABASE_SERVICE_ROLE_KEY=(.*)/);

const supabaseUrl = supabaseUrlMatch ? supabaseUrlMatch[1].trim() : '';
const supabaseServiceKey = supabaseServiceKeyMatch ? supabaseServiceKeyMatch[1].trim() : '';

if (!supabaseUrl || !supabaseServiceKey) {
  console.error("Missing supabase env vars");
  process.exit(1);
}

const supabase = createClient(supabaseUrl, supabaseServiceKey);

async function run() {
  try {
    const { data: users, error: userError } = await supabase.from('users').select('user_id').limit(1);
    
    if (userError) {
      console.error("Error fetching user:", userError);
      return;
    }

    if (!users || users.length === 0) {
      console.error("No users found to test with.");
      return;
    }

    const testUserId = users[0].user_id;

    const testKuis = {
      guru_id: testUserId,
      judul: "TEST KUIS",
      deskripsi: "Generated by Smartify AI",
      jenis_soal: "pilihan_ganda",
      tingkat_kesulitan: "medium",
      durasi_menit: 60,
      kkm: 70,
      jumlah_pilgan: 10,
      jumlah_uraian: 0,
      total_soal: 10,
      status: "draft",
      kode_kuis: "TEST12"
    };

    console.log("Attempting to insert:", testKuis);

    const { data, error } = await supabase
      .from('kuis')
      .insert(testKuis)
      .select()
      .single();

    if (error) {
      console.error("DB Error on insert kuis:", error);
    } else {
      console.log("Success! Inserted kuis:", data);
      await supabase.from('kuis').delete().eq('kuis_id', data.kuis_id);
      console.log("Cleaned up test row.");
    }

  } catch (e) {
    console.error("Exception:", e);
  }
}

run();
