import { NextRequest, NextResponse } from 'next/server';
import { GoogleGenerativeAI } from '@google/generative-ai';
import { supabaseServer as supabase } from '@/lib/supabase/server';
import { getUserFromToken } from '@/lib/auth/auth-service';

// Inisialisasi Gemini
const genAI = new GoogleGenerativeAI(process.env.GEMINI_API_KEY || '');

export async function POST(request: NextRequest) {
  try {
    const token = request.cookies.get('auth_token')?.value;
    if (!token) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
    }

    const user = await getUserFromToken(token);
    if (!user) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
    }

    const formData = await request.formData();
    const file = formData.get('file') as File;
    const title = formData.get('title') as string;
    const type = formData.get('type') as string; // pilihan_ganda, uraian, campuran
    const difficulty = formData.get('difficulty') as string;
    const totalQuestions = parseInt(formData.get('totalQuestions') as string);
    const duration = parseInt(formData.get('duration') as string);
    const kkm = parseInt(formData.get('kkm') as string);

    if (!file || !title) {
      return NextResponse.json({ error: 'File dan judul wajib diisi' }, { status: 400 });
    }

    const fileBuffer = await file.arrayBuffer();
    const base64Data = Buffer.from(fileBuffer).toString('base64');

    const model = genAI.getGenerativeModel({ model: 'gemini-2.5-flash' });

    let prompt = `Anda adalah seorang guru ahli. Buatlah soal ujian berdasarkan dokumen yang diberikan.
Judul Kuis: ${title}
Tingkat Kesulitan: ${difficulty}
Total Soal: ${totalQuestions}
Jenis Soal: ${type} (jika campuran, buat proporsi seimbang)

Kembalikan hasil HANYA DALAM FORMAT JSON ARRAY tanpa markdown (tanpa \`\`\`json) dengan skema berikut:
[
  {
    "teks_soal": "Pertanyaan soal...",
    "tipe_soal": "pilihan_ganda" // atau "uraian",
    "pilihan": [ // hanya jika tipe_soal = pilihan_ganda
      { "teks": "Pilihan A", "is_benar": true },
      { "teks": "Pilihan B", "is_benar": false },
      { "teks": "Pilihan C", "is_benar": false },
      { "teks": "Pilihan D", "is_benar": false },
      { "teks": "Pilihan E", "is_benar": false }
    ],
    "penjelasan": "Penjelasan mengapa jawaban tersebut benar...",
    "kunci_jawaban_essay": "Kunci jawaban / kata kunci jika uraian..."
  }
]
`;

    const result = await model.generateContent([
      prompt,
      {
        inlineData: {
          data: base64Data,
          mimeType: 'application/pdf',
        },
      },
    ]);

    const textResult = result.response.text();
    
    // Parsing JSON dengan aman
    let questionsData;
    try {
      const cleanJson = textResult.replace(/```json/gi, '').replace(/```/gi, '').trim();
      questionsData = JSON.parse(cleanJson);
    } catch (e) {
      console.error('Failed to parse AI response:', textResult);
      return NextResponse.json({ error: 'Gagal memproses respons dari AI.' }, { status: 500 });
    }

    // 1. Simpan ke tabel kuis
    const kodeKuis = Math.random().toString(36).substring(2, 8).toUpperCase();
    const { data: kuisData, error: kuisError } = await supabase
      .from('kuis')
      .insert({
        guru_id: user.user_id,
        judul: title,
        deskripsi: 'Generated by Smartify AI',
        jenis_soal: type,
        tingkat_kesulitan: difficulty,
        durasi_menit: duration,
        kkm: kkm,
        jumlah_pilgan: type === 'pilihan_ganda' ? totalQuestions : (type === 'campuran' ? Math.floor(totalQuestions / 2) : 0),
        jumlah_uraian: type === 'uraian' ? totalQuestions : (type === 'campuran' ? Math.ceil(totalQuestions / 2) : 0),
        total_soal: totalQuestions,
        status: 'draft',
        kode_kuis: kodeKuis
      })
      .select()
      .single();

    if (kuisError || !kuisData) {
      console.error('Error insert kuis:', kuisError);
      return NextResponse.json({ error: 'Gagal menyimpan kuis ke database' }, { status: 500 });
    }

    const kuisId = kuisData.kuis_id;

    // 2. Simpan setiap soal dan pilihannya
    for (let i = 0; i < questionsData.length; i++) {
      const q = questionsData[i];
      
      const { data: soalData, error: soalError } = await supabase
        .from('soal')
        .insert({
          kuis_id: kuisId,
          teks_soal: q.teks_soal,
          tipe_soal: q.tipe_soal,
          poin: 10,
          urutan: i + 1,
        })
        .select()
        .single();

      if (!soalError && soalData && q.tipe_soal === 'pilihan_ganda' && q.pilihan) {
        const soalId = soalData.soal_id;
        
        // Simpan pilihan jawaban
        const pilihanToInsert = q.pilihan.map((p: any, idx: number) => ({
          soal_id: soalId,
          teks_pilihan: p.teks,
          is_benar: p.is_benar,
          urutan: idx + 1
        }));

        await supabase.from('pilihan_jawaban').insert(pilihanToInsert);
        
        // Simpan penjelasan jika ada
        if (q.penjelasan) {
          await supabase.from('kunci_jawaban').insert({
            soal_id: soalId,
            jawaban_text: q.penjelasan,
            kata_kunci: []
          });
        }
      } else if (!soalError && soalData && q.tipe_soal === 'uraian') {
        const soalId = soalData.soal_id;
        await supabase.from('kunci_jawaban').insert({
          soal_id: soalId,
          jawaban_text: q.penjelasan || q.kunci_jawaban_essay || 'Tidak ada kunci jawaban',
          kata_kunci: q.kunci_jawaban_essay ? [q.kunci_jawaban_essay] : []
        });
      }
    }

    return NextResponse.json({ success: true, quizId: kuisId });

  } catch (error: any) {
    console.error('API Generate Error:', error);
    return NextResponse.json({ error: error.message || 'Terjadi kesalahan pada server' }, { status: 500 });
  }
}
